import Head from "next/head";
import Image from "next/image";
//import Avatar from "../components/Avatar";
import { useRef } from "react";
import { image } from "next/image";
//import Footer from "../components/Footer";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = e => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    console.log(term);
    if (!term) return;

    //if term is not empty
    router.push(`/search?term=${term}`); // also does put the search term in the address bar
  };
  return (
    <div className="flex flex-col justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/*LEFT DIV*/}
        <div className="flex space-x-5 items-center">
          <p className="link">Home</p>
          <p className="link"><a href="https://about.google/?utm_source=google-IN&utm_medium=referral&utm_campaign=hp-footer&fg=1">About</a></p>
        </div>
        {/*RIGHT DIV*/}
        <div className="flex space-x-5 items-center">
          <p className="link"><a href="https://mail.google.com/mail/?usp=installed_webapp">Gmail</a></p>
          <p className="link"><a href="https://www.google.co.in/imghp?hl=en&ogbl">Images</a></p>

          {/*ICONS*/}
          <a href="https://about.google/products/"><ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" /></a>

          {/*AVATAR*/}
          {/* <Avatar url="https://lh3.googleusercontent.com/a/AEdFTp7jD9N8vRjQbukqLyYAcTHzoJO6Iei5Ux_AqP7deu4=s371-p-rw-no" /> */}
        </div>
      </header>

      {/*BODY*/}
      <form className="flex flex-col items-center mt-40 flex-grow w-5/5">
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          width={300}
          height={100}
        />

        <div className="flex w-full mt-4 hover:shadow-lg focus-within:shadow-lg max-w-md border border-gray-200 px-5 py-3 sm:max-w-xl lg:max-w-xl rounded-full">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none"
          />
          <MicrophoneIcon className="h-5 text-gray-500" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button className="btn" onClick={search}>
            Google Search
          </button>
          <button className="btn" onClick={search}>
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      {/*BODY*/}

      {/*FOOTER*/}
      <footer />
    </div>
  );
}
